name:                alap-paper
version:             0.1.0.0
github:              "DCMLab/alap-paper-ismir19"
license:             BSD3
author:              "Christoph Finkensiep"
maintainer:          "christoph.finkensiep@epfl.ch"
copyright:           "Christoph Finkensiep"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/DCMLab/alap-paper-ismir19#readme>

dependencies:
- base >= 4.7 && < 5
- algebraic-graphs
- containers
- mtl
- HaTeX
- text

library:
  source-dirs: src

executables:
  make-graphs:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - alap-paper
